### ISSUE TITLE
Implement better storage mechanism for storing connections

### ISSUE THREAD

**Issue by akshay2000** [akshay2000/XBMCRemoteRT#14]
Currently, connections stored in a file which is not very good for concurrent access. This issue is to weigh different possibilities for storage of data.

**Comment by gabrielsadaka** [comment]
Any issues with using a local database? That would handle all of the concurrent access issues

**Comment by akshay2000** [comment]
Database seems like a nice solution. Question is, which one! Last time I checked SQLite came with it's own set of issues. You required hacky wrappers. You had to compile separately for different architectures. I also remember it breaking the designer view for Windows 8. Does someone have more recent news?

**Comment by gabrielsadaka** [comment]
I think with the designer you have to create explicit dummy data and define that in the XAM. As for the separate compilation I don't remember having to do any of that. This page doesn't seems rather straight forward https://msdn.microsoft.com/en-us/library/windows/apps/hh202876(v=vs.105).aspx.

**Comment by akshay2000** [comment]
That's not a right place to look into. Dummy data doesn't come into picture here. The designer view plainly just won't load for certain configurations. The 'Local Databases' (linked by you) did not have any of these problems. It's just that Microsoft removed the support in WinRT. In initial days, there was [no support](http://stackoverflow.com/questions/13660227/correct-way-to-use-databases-in-windows-8-and-windows-phone-8) for any local database at all. Then SQLite came along and gave us something. But that's clunky at best. If you're interested, [this post](http://stackoverflow.com/questions/13660227/correct-way-to-use-databases-in-windows-8-and-windows-phone-8) sheds some light on the caveats of using SQLite.  
I'm wondering if LexDB is a good solution.

**Comment by akshay2000** [comment]
On second thought, current file based implementation is good enough (ignoring occasional crash or two). If Windows 10 end up offering a robust first party database-like storage support, we will migrate to that API.

**Comment by gabrielsadaka** [comment]
When do you concurrently access the connections anyway?

**Comment by akshay2000** [comment]
@gabrielsadaka In a (very rare) scenario, a user may save a newly edited/created connection and try to navigate quickly to all connections. Here one thread is finishing the write of connection while another comes up and tries to read it. This causes trouble. But as long as this repo is concerned, I'm closing this issue. Expect to have a Windows 10 repo soon.
