### ISSUE TITLE
Voice search results list is unresponsive

### ISSUE THREAD

**Issue by christianprescott** [akshay2000/XBMCRemoteRT#25]
Steps to reproduce
* Perform a Cortana voice command that turns up multiple results. "Kodi play artist drake" in my case.
* "We found multiple..." message is displayed with results including "Drake", "Drake/The Weeknd", "Drake/Rihanna", and others.
* Tapping any of the artists has no effect on the player. 

![wp_ss_20150104_0001 1](https://cloud.githubusercontent.com/assets/2000583/5607240/c61ccb0c-9420-11e4-9dfe-2d2320f84f87.png)

**Comment by christianprescott** [comment]
Hope I'm not bugging you with these. Very excited for Cortana features and happy to contribute.

**Comment by akshay2000** [comment]
I had no idea there wasn't a handler for this! Thanks a lot for pointing that out. If you can make anything better, feel free. You're not bugging as long as you're helping!

**Comment by akshay2000** [comment]
Closed with pull request #26 by @christianprescott.
