### ISSUE TITLE
Allow multiple connection profiles

### ISSUE THREAD

**Issue by brinox** [akshay2000/XBMCRemoteRT#28]
As I am using multiple Kodi instances in my home, I would like to switch between the connection profiles. It would be nice, if one could choose a default connection, to which Cortana play requests are sent to.

**Comment by christianprescott** [comment]
"Switch Server" is being added as an app bar menu option on the home page. Will make it much more straightforward to change connections.

By default, Cortana sends requests to the most recent connection. You are asking for the ability to designate one connection to receive all Cortana requests?

**Comment by akshay2000** [comment]
Cortana *always* defaulting to one particular connection won't be a good idea. For example, user is in bedroom and connected to the server in that room. It won't make sense for Cortana to start movie in the kids' room. That's freaky!
I propose an alternate flow. In settings, first we set the behavior for every autoconnect (Cortana as well as regular app launch) - `recent connection` or `default connection`. This autoconnect rule is followed through all the autoconnects. So, If the session is not open (app completely closed and destroyed) Cortana as well as app launch will try the connection user has set in settings. If session is open with some server, all the requests (including Cortana) go to that server.

**Comment by christianprescott** [comment]
How about adding
1) a setting for "Cortana plays media on..." with option to select one from the list of connections or "most recent"
2) the ability to pin connections to start. Launching the app would connect to most recent, but launching from a pinned connection would connect to that host.

-----Original Message-----

**Comment by akshay2000** [comment]
1. Disturbs the integrity and causes confusion. All autoconnects should behave consistently. Cortana should interact with the same server as the rest of the app.
2. This frequently comes up in discussions, but there's never a good case for this. If app is off, all it takes is two taps to connect to particular server. All we can do is to reduce it to one tap with secondary tile. If the app is open, clicking 'switch server' is probably easier to actually switch the servers. Otherwise, you'd have to kill the app and relaunch it and hope that you have autoconnect turned off!

**Comment by brinox** [comment]
I really like the idea of connecting to the most recent Kodi instance having the ability to switch with a button in the app menu. Also, I think one needs a little indicator on the home screen to show which Server one is connected to, this avoids confusion and playing your favourite horror movie in the kid's room ;)

**Comment by akshay2000** [comment]
Great! So, I suggest you first try beta [here](http://wpbeta.me/kodi-assist-beta) and see if that suits your needs. After you're satisfied, you can close this issue yourself or suggest something if you need it.
As for the currently connected server, I'll try to find a place for it.

**Comment by brinox** [comment]
I signed up for the beta but it says you have to add me to the beta testers list so I can download the app directly.

**Comment by akshay2000** [comment]
Please wait for a bit. I'll need to add you to the list of beta testers. You'll get an email when that procedure is done.

**Comment by brinox** [comment]
The switching mechanism works like a charm, thank you! I will close this issue when you placed the server indicator like promised :)

**Comment by akshay2000** [comment]
I'm thinking of adding server name as an indicator. The question is, where to add it! Is there a place in your mind?

**Comment by brinox** [comment]
Here's an exmaple of the app [XBMC remote](http://www.windowsphone.com/en-us/store/app/xbmc-remote/64f736e7-df4a-414d-b51e-f21e22698bab) which shows a little indicator with servername and connection status in the upper left corner. Maybe that could be a little inspiration.

I doubt the indicator has to be seen in every view, the "currently playing" view shold be enough as it is the entry point. I marked the unused space in the view green, correct me if I'm wrong, maybe there is a place for it there.

![wp_ss_20150109_0003_green](https://cloud.githubusercontent.com/assets/2724840/5683751/c13cd56a-982a-11e4-9666-d32a0740169c.png)

**Comment by christianprescott** [comment]
Another option: server name in the place currently occupied by "kodi assist". If you don't want to lose the branding, maybe put "kodi assist" in small caps above like the album page, then larger name below it?

**Comment by akshay2000** [comment]
@christianprescott I thought this suggestion might come up. However, people give random names to their servers (asdf, server1, fvdnfdbik) and if those names are put here, that will make app really ugly. But I like this idea. If the name does look ugly, we can blame it on the person who named their server! Let's call in one of the coolest design guys out there. What do you suggest @AnaghSharma - where would you add the server name?
