### ISSUE TITLE
Preparing library when connecting to Kodi Assit

### ISSUE THREAD

**Issue by zumchikara** [akshay2000/XBMCRemoteRT#34]
I have my server set up correctly I believe. It seems to connect. It says "Preparing Library" and gets almost to the end of the bar but never goes any farther. I've rebooted my phone to make sure that wasn't the issue. I've let it sit for about 30 minutes with no change.

**Comment by zumchikara** [comment]
I was able to uninstall and reinstall the app and it started working.

**Comment by akshay2000** [comment]
It is strange that you had the issue. More strange is the fact that reinstall solved it. We're keeping this issue open in case other beta testers face the similar issue. If it's common among users, we might need to take measures. Tagging @christianprescott just in case.

**Comment by christianprescott** [comment]
Hm, 30 minutes is plenty long. So up to the point it got stuck, the bar was making (slow) progress right? @zumchikara do you have a password on your webserver or no?

I also would not have expected reinstall to change anything, but maybe another fix would be to clear temporary files through Storage Sense.

**Comment by akshay2000** [comment]
@christianprescott Actually, I enabled cache for everyone, password or not! Clearing temp files is something we can try. Although, many people have been complaining. I'm thinking of disabling cache and enabling authenticated bitmaps for all.

**Comment by zumchikara** [comment]
@christianprescott It did make "slow" progress. It took maybe a minute and a half to get up to let's say 95% and then just stops there. I closed the app several times and let the progress restart. Rebooted my phone. I finally just uninstalled and the reinstalled and it went right through and has been working fine since. Yes I do have username and password set in kodi.

**Comment by christianprescott** [comment]
Right, I remember, but I'm hoping there isn't a non-password flow that the cache could get hung up on. Sitting down now to review this and bitmap image.

**Comment by akshay2000** [comment]
@zumchikara Glad that it's working for you now. Everything is usually snappy and fast after the first load is done. However, you can try this one more thing. Let me warn you, this can be risky and might end up rendering the app in not working state. So, if you're up to it, you can try reproducing the issue by going to settings and refreshing the library.
@christianprescott I thought of the same thing. But then I had tested both with and without authentication. But if you choose to disable the cache, all you have to do is get rid of building cache at startup and comment a few lines in `GetImage` method.

**Comment by brinox** [comment]
After downloading the app update, it took ~5 minutes to prepare the library, that's okay for, as I've got a quite large amount of songs. 

But ***every time*** I open the app or switch to another server, the "preparing library" process takes about a minute again until I can start using the app again. To me, that is very annoying.

**Comment by akshay2000** [comment]
@brinox Thanks for reporting that Jan. I'll push an update with this fixed in next 24 hours. Please report back if issue goes away with next version.
@christianprescott I'm gonna push out a beta with cache disabled but AuthBitmap enabled throughout. Let's see if that performs.

**Comment by christianprescott** [comment]
What's going on in the background is Kodi Assist is ensuring the images for thumbnails, fan art, etc are cached. For everyone, this is nice because it really speeds up scrolling through image-heavy lists, but the real reason is it prepares some images for servers with passwords where they otherwise wouldn't show up at all. It's looking more and more like the cost outweighs the benefit and we should take another route.

**Comment by christianprescott** [comment]
@akshay2000 sounds good

**Comment by zumchikara** [comment]
Akshay2000 I'm at work at the moment, but when I get home ill try out what you said.

**Comment by zumchikara** [comment]
@akshay2000 I'm not seeing anything in the options to refresh. I did go into my tv shows and movies and there were refresh buttons there. Are those the ones you speak of? If so I did those and it said loading for maybe 10 seconds and then was finished.

**Comment by akshay2000** [comment]
@zumchikara No, not those. From the cover page (where you see now playing and all) open the app bar and open settings from there. There you'll find a huge button for refreshing library.

**Comment by zumchikara** [comment]
I have screenshots from that page. I don't see a refresh button. Can I send these somewhere?

**Comment by akshay2000** [comment]
You can attach on GitHhub comments. Drag and drop. Or, upload to Imgur ([Grin](http://www.windowsphone.com/en-us/store/app/grin/1148ec57-6099-44c9-9389-59ce7abf35e8) is nice app to do that) and post a link here! Here's my screenshot: http://imgur.com/XCEkO5D

**Comment by zumchikara** [comment]
![wp_ss_20150123_0002](https://cloud.githubusercontent.com/assets/4467003/5887882/dd867aaa-a3b5-11e4-8403-06b6a198ccf3.jpg)

**Comment by zumchikara** [comment]
Even if I turn autoconnect off, I don't have the option you have.

**Comment by akshay2000** [comment]
That is quite strange. Are you sure you're on the beta? In any case, try to go to store and [update](http://www.windowsphone.com/s?appid=8b5df5e3-e092-4afc-ba2e-7cbf14aa503d) the app. I have removed the refresh cache altogether. But the option to refresh it is still there. Check out the latest beta and see if that fixes your issue.

**Comment by christianprescott** [comment]
The refresh button appears only when authentication is in use. https://github.com/akshay2000/XBMCRemoteRT/blob/1545de82e50cb0a4c9b01e9427bcb2fbc9d05d8a/XBMCRemoteRT/XBMCRemoteRT.WindowsPhone/Pages/SettingsPivot.xaml.cs#L252-255

**Comment by akshay2000** [comment]
@christianprescott I implemented cache for everyone, avoiding any distinction between authenticated and non-authenticated users. And anyway, he's using the authentication.
Lastly, latest version shouldn't have any problem at all.

**Comment by zumchikara** [comment]
http://i.imgur.com/i5EO0cb.jpg

Apparently I had his Kodi Assist. I know have one that's labeled beta.

As for that error, I got it after 3 minutes. I know kodi is working because I can control it with the remote side.

**Comment by akshay2000** [comment]
This error pops up sometimes for no reason. I'll take care of that in another issue. However, let's make sure that this issue is resolved first.
1. Do your images load as expected?
2. Has the annoying 'preparing library' step gone away?
3. App is usable?

**Comment by zumchikara** [comment]
Yes the app seems to work fine. The refresh never completes, but images do load.

**Comment by akshay2000** [comment]
@zumchikara If you are not experiencing the issue in latest beta, can you close it?

**Comment by zumchikara** [comment]
Can do. All seems to be functioning correctly.
