### ISSUE TITLE
Implement data virtualization for larger lists

### ISSUE THREAD

**Issue by akshay2000** [akshay2000/XBMCRemoteRT#41]
Large lists (like Movies and TV Shows) may give out of memory exception while loading. Data virtualization should help mitigate this problem. Random Access Virtualization seems like a viable solution.

**Comment by gabrielsadaka** [comment]
Sounds good, looking at https://msdn.microsoft.com/en-us/library/windows/apps/xaml/hh780657.aspx if we implement ISupportIncrementalLoading (https://msdn.microsoft.com/en-us/library/windows/apps/xaml/windows.ui.xaml.data.isupportincrementalloading.aspx) for all of the Lists that need virtualization all we need to do is keep track of the current starting index of the data loaded and when LoadMoreItemsAsync is called we just use http://kodi.wiki/view/JSON-RPC_API/v6#List.Limits to only load a certain subset of all of the Movies/TV Shows.

**Comment by akshay2000** [comment]
Problem with incremental loading is that it's not transparent. User *knows* data is being loaded. Scrollbar jumps around to accommodate newly added items. That's why I am looking into random access virtualization. I'll see what fits the best.

**Comment by gabrielsadaka** [comment]
Have you found any existing implementations of IObservableVector worth using? All of the implementations I have found seem to be incomplete.

**Comment by akshay2000** [comment]
@gabrielsadaka Well, you feel my pain! I'll keep looking for a while. In the end, if nothing else, incremental load it shall be.

**Comment by gabrielsadaka** [comment]
It's really surprising Microsoft hasn't built their own implementation of it.

**Comment by akshay2000** [comment]
Okay, here's the plan. Let's implement incremental load with sufficiently large base count. That way, smaller libraries remain largely unaffected. Only bigger libraries get incremental load. But then again, library with more than 300 items is barely usable. The user is likely to end up using search. So, they don't have to see the incremental load either.

**Comment by gabrielsadaka** [comment]
That's a good point I can't imagine many people wanting to scroll through their whole library anyway so incremental load should be fine. Maybe set the base count to 100. Does Kodi work well with Movie genres? Maybe implementing a view with Genres as pivots or a drop down list so they can limit how many movies are shown in the list would be useful as well.

**Comment by akshay2000** [comment]
Kodi does work with generes. But I recently asked a few users to lend me their libraries. No matter how you slice that set of movies, you're gonna end up with a mess. I think current views + incremental load + robust search should get us started.

**Comment by gabrielsadaka** [comment]
Agreed, how's the incremental loading coming along?

**Comment by akshay2000** [comment]
[Pretty good](https://github.com/akshay2000/XBMCRemoteRT/tree/data-virtualization). I am also migrating search to Kodi server APIs instead of performing it locally. Meanwhile, we need to spark a discussion on #14.
