### ISSUE TITLE
WOL doesn't accept 0 as first character in mac id

### ISSUE THREAD

**Issue by Rudders1973** [akshay2000/XBMCRemoteRT#42]
Under wake on Lan it won't let me add 00 for the first numbers. It keeps deleting the first 0 so won't WOL. If I added a 2 for example then it keeps 20 just not 00.

**Comment by akshay2000** [comment]
@Rudders1973 Music crash has been moved to #43. Please track it there.

**Comment by brinox** [comment]
I think I know the where this originates from, I'm going to fix it soon.

**Comment by Rudders1973** [comment]
Great stuff. Thanks

**Comment by akshay2000** [comment]
@brinox Thanks. I'm not sure if GitHub allows you to do that, but if it does, please assign it to yourself so that someone else doesn't pick this up.  
@Rudders1973 Just so you know, @brinox is the reason we even have this feature.

**Comment by brinox** [comment]
@akshay2000 I am not able/allowed to assign myself to this issue, I think only you can do that as you're the owner of the repo

**Comment by akshay2000** [comment]
@brinox Never mind then! I can't do that either. I think it's only for the people who have been added as contributors and have direct access to repo. Anyway, open a pull request as usual when you're ready.

**Comment by Rudders1973** [comment]
Email failed, what address can I send it too.

**Comment by Rudders1973** [comment]
Any news on the mac address fix where it won't allow 2 00's first? Thanks.

**Comment by brinox** [comment]
Here you go :)

**Comment by Rudders1973** [comment]
Where is the fix?

**Comment by akshay2000** [comment]
The fix has just been merged with pull request #44. Thanks @brinox, I will update the app soon.

**Comment by Rudders1973** [comment]
Lovely. Much appreciated.

**Comment by akshay2000** [comment]
@Rudders1973 The fix has been published in Store. This is included in public version, not the beta. Check it out and close the issue if it's fixed.

**Comment by Rudders1973** [comment]
Thank you. Music library loading fixed and WOL now fixed
