### ISSUE TITLE
Music pivot crashes while loading large music library

### ISSUE THREAD

**Issue by akshay2000** [akshay2000/XBMCRemoteRT#43]
When loading music library it crashes and bombs out every time.

**Comment by akshay2000** [comment]
@Rudders1973 We are going to need more details here.

1.How big is your audio library?
2. When did you start experiencing the crash? Did the app work before?
3. Can you try cleaning up the music library and check whether the crash persists?

**Comment by Rudders1973** [comment]
Music collection is just under 40,000 mp3's.
This crash happened from day one but ok in a different remote app I tested with.
I have tried cleaning and re-scanning the library but still get the app closing.

**Comment by akshay2000** [comment]
Would it be possible for you to send me your music db. It just contains the metadata about your music - not the music itself. [Here](http://kodi.wiki/view/Userdata) are the instructions on where to find the databases. I think MyMusic#.db would suffice for testing.

**Comment by Rudders1973** [comment]
I have emailed the file to you.

**Comment by akshay2000** [comment]
@Rudders1973 I have dropped you the email. You may reply to it. If that fails, upload file somewhere (Dropbox, OneDrive, etc.) and send me the link in email.

**Comment by Rudders1973** [comment]
Just to let you know I removed the music library from Kodi and deleted all the mymusic db files.i then rebooted and recreated the music library on Kodi. The app still closes while reading the whole library. Have you managed to test yet? Thanks.

**Comment by akshay2000** [comment]
Don't worry! I'm on it. The fix is [ready](https://github.com/akshay2000/XBMCRemoteRT/commit/895e756423bf04101e6294a9486a057228b8fa81) and it's in the code! It will be delivered in the app soon. Moreover, awesome stuff is coming. Hang on tight.

**Comment by Rudders1973** [comment]
Ooooo, nice. Sounds good. Link forward to it. Thanks.
