### ISSUE TITLE
Migrate Windows project to new Filter and Sort based APIs

### ISSUE THREAD

**Issue by akshay2000** [akshay2000/XBMCRemoteRT#46]
RPCWrapper APIs no more take Filter and Sort in form of JObjects. Instead, concrete types have been introduced. Windows Phone project has already been refactored to use these new APIs. However, the Windows side remains unaltered. Naturally, the Windows Project doesn't compile.
This issue is to track progress on fixing those errors and refactor the calls to new APIs. An example can be seen at commit: 7f045fa.
The shared code is not to be touched.

**Comment by gabrielsadaka** [comment]
Are you planning on migrating the app to the new Windows Universal adaptive model?

**Comment by akshay2000** [comment]
@gabrielsadaka Do not start working on this just yet. I have a feeling someone else is going to take this up. With that said, let's discuss Windows 10.
Of course, we are going to migrate to UAP soon. I am waiting for the Windows 10 Insider Preview to go stable enough to be used for development. Right now, it's just slow and rough.
Then there's design. They don't seem to have made there mind about it just yet. Once that's stabilized enough, we may start developing.
As long as this issue is concerned, I don't think everyone is magically going to jump to Windows 10 as soon as it's out. So, while adoption phase is going on, we can have presence in Store. Meanwhile, @christianprescott has done some UI refining work already. If we integrate current work (that is mostly done by you) with his and fix minor issues like this one, we may actually have a quick release.

**Comment by gabrielsadaka** [comment]
Okay fair enough, I might start building a mini project with the new adaptive layouts to get a feel for them. I already designed the Windows 8 app to scale to various resolutions so it hopefully shouldn't take much work to move it over to the new layout.
