### ISSUE TITLE
Implement Files RPCWrapper

### ISSUE THREAD

**Issue by akshay2000** [akshay2000/XBMCRemoteRT#47]
An empty stub has been added [here](https://github.com/akshay2000/XBMCRemoteRT/blob/master/XBMCRemoteRT/XBMCRemoteRT.Shared/RPCWrappers/Files.cs) for the class. Details about the API provided by Kodi can be found [here](kodi.wiki/view/JSON-RPC_API/v6#Files).
All the methods are to be styled exactly like the methods in other RPCWrapper classes (viz. AudioLibrary and VideoLibrary).

**Comment by gabrielsadaka** [comment]
I've started working on the files JSON API and also began working on creating windows phone pages to browse the files and eventually play the files. Are there any other features that you had in mind?

https://github.com/gabrielsadaka/XBMCRemoteRT/commit/1c5c14b90d742eb87ba224b797d9bf21173219c6

**Comment by akshay2000** [comment]
That's great. Let's implement the browsing first. make sure the APIs adhere to the style of other APIs. Let's see how this goes.

**Comment by gabrielsadaka** [comment]
Okay well I have the file browser page there now, only thing left is to implement back button navigation for going back to the previous folder and playing the file when clicked on it.

**Comment by akshay2000** [comment]
Bug:

1.Browse to anything. (Music > Some Folder > Some Child Folder)
2. Go back to sources.
3. Browse to some other source. (TV Shows > Some Folder)
4. You're presented with the old folders. (Music in this case)
