### ISSUE TITLE
Background of appbar flyout menu opacity

### ISSUE THREAD

**Issue by Sranshaft** [akshay2000/XBMCRemoteRT#50]
The background's opacity is set too low causing the text of the menu to become illegible.

**Comment by akshay2000** [comment]
Which appbar are we talking about here? Can you provide a screenshot?

**Comment by Sranshaft** [comment]
Here are those screenshots. 

http://1drv.ms/1cB7eVd

**Comment by Sranshaft** [comment]
Here's a better example. 

http://1drv.ms/1H6NFAM

As you can see, with the fanart displayed on the home pivot the menu's text become nearly illegible.

**Comment by akshay2000** [comment]
I can increase the opacity, I suppose!
