### ISSUE TITLE
Multiple copies of the same TV show in list

### ISSUE THREAD

**Issue by Sranshaft** [akshay2000/XBMCRemoteRT#51]
As the issue title says, I'm getting multiple copies of the same tv show item in the list.

**Comment by akshay2000** [comment]
1. Please check if your server shows the same. Highly likely, the server has duplicates too.
2. Please give a screenshot.

**Comment by Sranshaft** [comment]
There are no duplicates on my Kodi installs. Only in the app. Will get a screenshot for you when I'm able.

**Comment by Sranshaft** [comment]
Here are a couple screenshots showing the repeating titles.

http://1drv.ms/1Qvj54G

As you can see, it's populating the list and then jumps back and started populating the list again with duplicate titles before resuming normally. It does this throughout the entire list every 10-15 items.

**Comment by akshay2000** [comment]
Interesting. Details:

1. Roughly, how many TV shows do you have in there?
2. Does the same or similar issue occur with movies?
3. Can you try cleaning the video library and check if the problem goes away?
4. If possible, try rebuilding the library from scratch? (I know, this is nuclear!)
5. Send a copy of video database so that I can try debugging the exact issue.

**Comment by Sranshaft** [comment]
1. A little over 300 tv shows.
2. Works fine for movies and music.
3. Same issue after cleaning.
4. Sorry but I'm not rebuilding the library from scratch...the database works fine in all other Kodi apps.
5. I can get you a couple of the database but as I said it works fine in other apps.

I had a look at your code and your call to grab the TV show list is different to your call to grab the movies list.

In movies:

List<Movie> moreMovies = await VideoLibrary.GetMovies(limits: limits, filter: filter, sort: sort);

In TV show:

var moreShows = await VideoLibrary.GetTVShows(limits, filter, sort);

Shouldn't it be:

var moreShows = await VideoLibrary.GetTVShows(limits: limits, filter: filter, sort: sort);

**Comment by akshay2000** [comment]
The calling mechanisms for movies and TV shows are only syntactically different at face value. They mean the same.
Most likely, other apps obtain the lists in a different way that this. So, it would be great if you send out your videos database for testing. Also, it helps if you upgrade to latest Kodi version (stable) available before sending the database.

**Comment by akshay2000** [comment]
Cannot reproduce without sample database.
