### ISSUE TITLE
"Info" button missing from remote

### ISSUE THREAD

**Issue by jlnprssnr** [akshay2000/XBMCRemoteRT#54]
Kodi allows you to get information about a movie when pressing "i" on your keyboard (http://kodi.wiki/view/Keyboard_controls#Default_keyboard_controls), this should be available here. Media Center Remote (https://www.microsoft.com/en-us/store/apps/media-center-remote/9wzdncrdqz3d) has this, too.

**Comment by akshay2000** [comment]
@jlnprssnr You may go to settings and enable that button. The icon looks like a page. Please close this issue if this resolves the problem.

**Comment by akshay2000** [comment]
Closing the issue.
