### ISSUE TITLE
suspend, shutdown, reboot not implemented

### ISSUE THREAD

**Issue by zbabac** [akshay2000/XBMCRemoteRT#56]
Advanced menu has Shutdown option that is not working (Resource.resw is missing shutdown string).
I suggest to fix Shutdown and also add Suspend and Reboot Kodi server option in Advanced menu on Remote in a way that:
- shutdown invokes Kodi server power-off;
- suspend invokes Kodi server sleep (or suspend, depending on OS);
- reboot invokes Kodi server reboot
I propose that I prepare new commit in master branch that will add those options.

**Comment by akshay2000** [comment]
This sounds great. I'm not entirely sure about the reboot feature yet. I am aware that Kodi does support this feature but it really seems out of scope for the app. As it stands, there are already many things in the menu. I'd rather not clutter it up.  
Moreover, no one has requested that feature. So, It's safe to exclude it for now. Go ahead with shut down and suspend.
