### ISSUE TITLE
App crashes when pressing Play/Pause button in certain scenarios

### ISSUE THREAD

**Issue by zbabac** [akshay2000/XBMCRemoteRT#59]
I noticed this issue when playing streaming content, like youtube or other streaming media. Unhandled exception occurs only if artist data, etc. is missing. 
It happens both at "Now Playing" pivot page and at Remote (InputPage).

It occurs in:
private static async Task RefreshPlayerItem(Players player) because result item has null value. It is easily detectable when inserting try/catch.
It can be quickly resolved by inserting try/catch in this method. I suggest inserting try/catch also in:
public static async Task RefreshPlayerState() and in
public async static Task<JObject> GetItem(Players player, JArray properties) (in Player.cs), where some return value must be passed

**Comment by akshay2000** [comment]
While I'm not sure if this is the best way to go about it, I'd suggest you to go ahead and fix it. Create a pull request when you're ready.
