### ISSUE TITLE
app crash on open

### ISSUE THREAD

**Issue by rdgarfinkel** [akshay2000/XBMCRemoteRT#60]
Currently, when I try opening Kodi Assist, it crashes. There's no error that shows up, just sends me back to the start screen. This takes place whenever my phone is connected to the wireless network at home. If I turn wireless off, there is no crash. Ideas?

**Comment by akshay2000** [comment]
This is probably due to your server playing tricks. Try disabling the auto-connect and see how it behaves.

**Comment by rdgarfinkel** [comment]
Auto connect in the app or is this in kodi settings? I didn't see an option in app settings, anyway.

**Comment by akshay2000** [comment]
You'll find it in settings > miscellaneous in the app.

**Comment by rdgarfinkel** [comment]
![wp_ss_20151201_0002](https://cloud.githubusercontent.com/assets/7954223/11511947/cb82a328-9839-11e5-8ff8-53bee18eae6a.png)
I don't see options for settings anywhere, am I looking in the right area? Or does settings only show up when it's connected to a server?

**Comment by akshay2000** [comment]
You're right. Settings only show up after you're connected. Can you try connecting to a different server. That should do it.

**Comment by rdgarfinkel** [comment]
Ok, yep, somethings screwy with the other server, it worked fine with another server. I'll try nuking the Kodi configs to see if that makes it work again. Thanks! :)

**Comment by akshay2000** [comment]
Let's close this issue then!
